dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

install:
- opam init
- opam install js_of_ocaml

script:
- git clone https://github.com/coq/coq
- git checkout v8.9
- echo hello
