dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/coq
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

install:
- opam init -y
- eval $(opam env)
- opam install -y camlp5
- opam install -y num
- opam install -y js_of_ocaml
- git clone https://github.com/coq/coq
- cd coq
- git checkout v8.9
- ./configure -local -byte-only
- make
- ls bin

script:
- echo hello
