dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

install:
- opam init -y
- eval $(opam env)
- opam install -y js_of_ocaml

script:
- git clone https://github.com/coq/coq
- cd coq
- git checkout v8.9
- ls bin
- ./configure --help
- echo hello
