dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/coq
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

install:
- opam init -y
- eval $(opam env)
- opam install -y camlp5
- opam install -y num
- opam install -y js_of_ocaml
- echo cd
- echo git clone https://github.com/coq/coq
- echo cd coq
- echo git checkout v8.9
- echo ./configure -local -byte-only
- echo make
- ls bin

script:
- pwd
- js_of_ocaml ~/coq/bin/coqtop.byte
- echo hello
